import Foundation

public enum LocalizableKey: String, Sendable, CaseIterable {
    case appName = "app.name"
    case appTagline = "app.tagline"

    case menuBuscar = "menu.buscar"
    case menuBuscarLoading = "menu.buscar.loading"

    case menuArchivoNuevaTransaccion = "menu.archivo.nueva_transaccion"
    case menuArchivoHistorial = "menu.archivo.historial"
    case menuArchivoSuscripciones = "menu.archivo.suscripciones"
    case menuArchivoPrestamos = "menu.archivo.prestamos"
    case menuArchivoReportes = "menu.archivo.reportes"
    case menuArchivoConfiguracion = "menu.archivo.configuracion"

    case menuIr = "menu.ir"
    case menuIrDashboard = "menu.ir.dashboard"
    case menuIrHistorial = "menu.ir.historial"
    case menuIrSuscripciones = "menu.ir.suscripciones"
    case menuIrPrestamos = "menu.ir.prestamos"
    case menuIrReportes = "menu.ir.reportes"

    case menuHerramientas = "menu.herramientas"
    case menuHerramientasCambiarDenominaciones = "menu.herramientas.cambiar_denominaciones"
    case menuHerramientasImportarWindows = "menu.herramientas.importar_windows"
    case menuHerramientasDiagnostico = "menu.herramientas.diagnostico"

    case commonAceptar = "common.aceptar"
    case commonCancelar = "common.cancelar"
    case commonCerrar = "common.cerrar"
    case commonSi = "common.si"
    case commonNo = "common.no"
    case commonLimpiar = "common.limpiar"
    case commonRecargar = "common.recargar"
    case commonRecargarHint = "common.recargar.hint"
    case commonActualizado = "common.actualizado"
    case commonActualizadoHint = "common.actualizado.hint"
    case commonGuardar = "common.guardar"
    case commonGuardando = "common.guardando"
    case commonAtras = "common.atras"
    case commonContinuar = "common.continuar"
    case commonListo = "common.listo"
    case commonEditar = "common.editar"
    case commonEliminar = "common.eliminar"
    case commonDesactivar = "common.desactivar"
    case commonActivar = "common.activar"

    case commonDiaSingular = "common.dia.singular"
    case commonDiaPlural = "common.dia.plural"
    case commonMesSingular = "common.mes.singular"
    case commonMesPlural = "common.mes.plural"

    case commonTipo = "common.tipo"
    case commonFecha = "common.fecha"
    case commonCategoria = "common.categoria"
    case commonDenominaciones = "common.denominaciones"

    case errorAceptarTitulo = "error.titulo.critical"
    case errorWarningTitulo = "error.titulo.warning"
    case errorInfoTitulo = "error.titulo.info"
    case errorBotonAceptar = "error.boton.aceptar"
    case errorBotonIgnorar = "error.boton.ignorar"
    case errorBotonEntendido = "error.boton.entendido"

    case enumTipoIngreso = "enum.tipo.ingreso"
    case enumTipoGasto = "enum.tipo.gasto"
    case enumMetodoEfectivo = "enum.metodo.efectivo"
    case enumMetodoTarjeta = "enum.metodo.tarjeta"
    case enumPrestamoMeDeben = "enum.prestamo.me_deben"
    case enumPrestamoDebo = "enum.prestamo.debo"
    case enumFrecuenciaMensual = "enum.frecuencia.mensual"
    case enumFrecuenciaTrimestral = "enum.frecuencia.trimestral"
    case enumFrecuenciaAnual = "enum.frecuencia.anual"
    case enumEstadoEnMeta = "enum.estado.en_meta"
    case enumEstadoCerca = "enum.estado.cerca"
    case enumEstadoEnRiesgo = "enum.estado.en_riesgo"
    case enumEstadoCategoriaInfo = "enum.estado.categoria.info"
    case enumEstadoCategoriaWarning = "enum.estado.categoria.warning"
    case enumEstadoCategoriaCritical = "enum.estado.categoria.critical"

    case categoriaComida = "categoria.comida"
    case categoriaTransporte = "categoria.transporte"
    case categoriaVivienda = "categoria.vivienda"
    case categoriaServicios = "categoria.servicios"
    case categoriaSalud = "categoria.salud"
    case categoriaEducacion = "categoria.educacion"
    case categoriaEntretenimiento = "categoria.entretenimiento"
    case categoriaCompras = "categoria.compras"
    case categoriaRopa = "categoria.ropa"
    case categoriaTrabajo = "categoria.trabajo"
    case categoriaFreelance = "categoria.freelance"
    case categoriaInversiones = "categoria.inversiones"
    case categoriaRegalos = "categoria.regalos"
    case categoriaMascotas = "categoria.mascotas"
    case categoriaOtros = "categoria.otros"

    case dashboardResumen = "dashboard.resumen"
    case dashboardSaldoTotal = "dashboard.saldo.total"
    case dashboardEfectivo = "dashboard.efectivo"
    case dashboardTarjeta = "dashboard.tarjeta"
    case dashboardBalanceReal = "dashboard.balance.real"
    case dashboardDeuda = "dashboard.deuda"
    case dashboardProyeccionMes = "dashboard.proyeccion.mes"
    case dashboardRiesgoMeta = "dashboard.riesgo.meta"
    case dashboardFaltan = "dashboard.faltan"
    case dashboardDia = "dashboard.dia"
    case dashboardIngresosEsperados = "dashboard.ingresos.esperados"
    case dashboardGastosEsperados = "dashboard.gastos.esperados"
    case dashboardSuscripciones = "dashboard.suscripciones"
    case dashboardSimulador = "dashboard.simulador.titulo"
    case dashboardSimuladorSubtitulo = "dashboard.simulador.subtitulo"
    case dashboardSimuladorEscenario = "dashboard.simulador.escenario"
    case dashboardConfigurarMeta = "dashboard.configurar.meta"
    case dashboardAcciones = "dashboard.acciones"
    case dashboardCargando = "dashboard.cargando"
    case dashboardNotificacionesTitulo = "dashboard.notificaciones.titulo"
    case dashboardNotificacionesDescartar = "dashboard.notificaciones.descartar"
    case dashboardMesActual = "dashboard.mes.actual"
    case dashboardIngresos = "dashboard.ingresos"
    case dashboardGastos = "dashboard.gastos"
    case dashboardNeto = "dashboard.neto"
    case dashboardHistorico = "dashboard.historico"
    case dashboardIngresado = "dashboard.ingresado"
    case dashboardGastado = "dashboard.gastado"
    case dashboardPrestamos = "dashboard.prestamos"
    case dashboardPrestamosPendientes = "dashboard.prestamos.pendientes"
    case dashboardSuscripcionesActivas = "dashboard.suscripciones.activas"
    case dashboardSuscripcionesPorVencer = "dashboard.suscripciones.por_vencer"
    case dashboardSuscripcionesMensual = "dashboard.suscripciones.mensual"
    case dashboardInventario = "dashboard.inventario"
    case dashboardInventarioTotal = "dashboard.inventario.total"
    case dashboardInventarioVacio = "dashboard.inventario.vacio"
    case dashboardNuevaTransaccion = "dashboard.nueva.transaccion"
    case dashboardHistorial = "dashboard.historial"
    case dashboardReporte = "dashboard.reporte"
    case dashboardCambiarBilletes = "dashboard.cambiar.billetes"
    case dashboardCambiarBilletesHint = "dashboard.cambiar.billetes.hint"

    case cargandoBaseDatos = "cargando.base_datos"
    case cargandoOnboarding = "cargando.onboarding"
    case cargandoDashboard = "cargando.dashboard"
    case errorReintentar = "error.reintentar"
    case errorAlgoSalioMal = "error.algo_salio_mal"

    case historialTitulo = "historial.titulo"
    case historialBuscar = "historial.buscar"
    case historialTodos = "historial.todos"
    case historialFiltroIngresos = "historial.filtro.ingresos"
    case historialFiltroGastos = "historial.filtro.gastos"
    case historialCategoria = "historial.categoria"
    case historialCategoriaTodas = "historial.categoria.todas"
    case historialOrden = "historial.orden"
    case historialOrdenRecientes = "historial.orden.recientes"
    case historialOrdenAntiguas = "historial.orden.antiguas"
    case historialOrdenMayor = "historial.orden.mayor"
    case historialOrdenMenor = "historial.orden.menor"
    case historialFiltroMes = "historial.filtro.mes"
    case historialConteoTransacciones = "historial.conteo.transacciones"
    case historialVacio = "historial.vacio"
    case historialFechaCompleta = "historial.fecha_completa"

    case formTxNueva = "formTx.nueva"
    case formTxEditar = "formTx.editar"
    case formTxSeccionFecha = "formTx.seccion.fecha"
    case formTxHora = "formTx.hora"
    case formTxConcepto = "formTx.concepto"
    case formTxSeccionMonto = "formTx.seccion.monto"
    case formTxPlaceholderCategoria = "formTx.placeholder.categoria"
    case formTxSeccionCategoria = "formTx.seccion.categoria"
    case formTxSeccionMetodo = "formTx.seccion.metodo"
    case formTxMetodo = "formTx.metodo"

    case cambioBilleteQuitar = "cambio.billete.quitar"
    case cambioBilleteAgregar = "cambio.billete.agregar"
    case cambioBilleteAplicar = "cambio.billete.aplicar"
    case cambioBilleteTotalQuitado = "cambio.billete.total.quitado"
    case cambioBilleteTotalAgregado = "cambio.billete.total.agregado"
    case cambioBilleteSaldoNeto = "cambio.billete.saldo.neto"
    case cambioBilleteBalanceOk = "cambio.billete.balance.ok"
    case cambioBilleteBalanceError = "cambio.billete.balance.error"
    case cambioBilleteConcepto = "cambio.billete.concepto"
    case cambioBilleteDisponible = "cambio.billete.disponible"
    case cambioBilleteInventarioActual = "cambio.billete.inventario.actual"

    case desgloseSubtotal = "desglose.subtotal"
    case desgloseAuto = "desglose.auto"
    case desgloseFaltan = "desglose.faltan"

    case formSubNueva = "formSub.nueva"
    case formSubEditar = "formSub.editar"
    case formSubConcepto = "formSub.concepto"
    case formSubCategoria = "formSub.categoria"
    case formSubSeccionMonto = "formSub.seccion.monto"
    case formSubEquivale = "formSub.equivale"
    case formSubPorMes = "formSub.por_mes"
    case formSubFrecuencia = "formSub.frecuencia"
    case formSubTipo = "formSub.tipo"
    case formSubInicio = "formSub.inicio"
    case formSubProximoCobro = "formSub.proximo_cobro"
    case formSubDuracion = "formSub.duracion"
    case formSubDuracionIndefinida = "formSub.duracion_indefinida"
    case formSubActiva = "formSub.activa"
    case formSubInactiva = "formSub.inactiva"
    case formSubFooterDuracion = "formSub.footer.duracion"

    case susTitulo = "sus.titulo"
    case susNueva = "sus.nueva"
    case susResumenMensual = "sus.resumen.mensual"
    case susResumenActivas = "sus.resumen.activas"
    case susResumenPorVencer = "sus.resumen.por_vencer"
    case susResumenProximas = "sus.resumen.proximas"
    case susResumenProximasLabel = "sus.resumen.proximas_label"
    case susResumen3dias = "sus.resumen.3dias"
    case susFiltro = "sus.filtro"
    case susFiltroTodas = "sus.filtro.todas"
    case susFiltroActivas = "sus.filtro.activas"
    case susFiltroInactivas = "sus.filtro.inactivas"
    case susFiltroVencidas = "sus.filtro.vencidas"
    case susFiltroPorVencer = "sus.filtro.por_vencer"
    case susVacio = "sus.vacio"
    case susRegistrarCobro = "sus.registrar_cobro"
    case susVencidaHaceSingular = "sus.vencida.hace.singular"
    case susVencidaHacePlural = "sus.vencida.hace.plural"
    case susVenceHoy = "sus.vence.hoy"
    case susVenceManana = "sus.vence.manana"
    case susEnDias = "sus.en.dias"
    case susPorMes = "sus.por.mes"
    case susInactiva = "sus.inactiva"

    case prestamoTitulo = "prestamo.titulo"
    case prestamoNuevo = "prestamo.nuevo"
    case prestamoAfectaBalance = "prestamo.afecta_balance"
    case prestamoAfectaBalanceDesc = "prestamo.afecta_balance.desc"
    case prestamoNuevoTitulo = "prestamo.nuevo.titulo"
    case prestamoEditarTitulo = "prestamo.editar.titulo"
    case prestamoSeccionPersona = "prestamo.seccion.persona"
    case prestamoPersonaPlaceholder = "prestamo.persona.placeholder"
    case prestamoConceptoPlaceholder = "prestamo.concepto.placeholder"
    case prestamoSeccionMonto = "prestamo.seccion.monto"
    case prestamoSaldoPendiente = "prestamo.saldo_pendiente"
    case prestamoSeccionPagado = "prestamo.seccion.pagado"
    case prestamoSeccionPagadoFooter = "prestamo.seccion.pagado.footer"
    case prestamoSeccionNotas = "prestamo.seccion.notas"
    case prestamoSeccionFecha = "prestamo.seccion.fecha"
    case prestamoSinPrestamos = "prestamo.sin_prestamos"
    case prestamoCantidad = "prestamo.cantidad"
    case prestamoAfecta = "prestamo.afecta"
    case prestamoPendiente = "prestamo.pendiente"
    case prestamoPagado = "prestamo.pagado"
    case prestamoErrorPersona = "prestamo.error.persona"
    case prestamoErrorMonto = "prestamo.error.monto"
    case prestamoErrorPagado = "prestamo.error.pagado"

    case configTitulo = "config.titulo"
    case configSubtitulo = "config.subtitulo"
    case configSeccionMeta = "config.seccion.meta"
    case configMetaDesc = "config.meta.desc"
    case configMetaPlaceholder = "config.meta.placeholder"
    case configSeccionHistorico = "config.seccion.historico"
    case configHistoricoDesc = "config.historico.desc"
    case configMeses = "config.meses"
    case configMesesOpcion = "config.meses.opcion"
    case configNotificaciones = "config.notificaciones"
    case configNotificacionesDesc = "config.notificaciones.desc"
    case configErrorCargar = "config.error.cargar"
    case configErrorMeta = "config.error.meta"

    case proyeccionMeta = "proyeccion.meta"
    case proyeccionEnMeta = "proyeccion.en_meta"
    case proyeccionCerca = "proyeccion.cerca"
    case proyeccionEnRiesgo = "proyeccion.en_riesgo"
    case proyeccionError = "proyeccion.error"
    case proyeccionSignoPositivo = "proyeccion.signo.positivo"
    case proyeccionSignoNegativo = "proyeccion.signo.negativo"
    case proyeccionMsgCerrasteMes = "proyeccion.msg.cerraste_mes"
    case proyeccionMsgPorEncima = "proyeccion.msg.por_encima"
    case proyeccionMsgPorDebajo = "proyeccion.msg.por_debajo"
    case proyeccionMsgRiesgo = "proyeccion.msg.riesgo"

    case reportesTitulo = "reportes.titulo"
    case reportesSubtitulo = "reportes.subtitulo"
    case reportesPdf = "reportes.pdf"
    case reportesCsv = "reportes.csv"
    case reportesSecciones = "reportes.secciones"
    case reportesSeccionResumen = "reportes.seccion.resumen"
    case reportesSeccionDetalle = "reportes.seccion.detalle"
    case reportesSeccionPrestamos = "reportes.seccion.prestamos"
    case reportesSeccionSuscripciones = "reportes.seccion.suscripciones"
    case reportesSeccionInventario = "reportes.seccion.inventario"
    case reportesSeccionProyeccion = "reportes.seccion.proyeccion"
    case reportesExportar = "reportes.exportar"
    case reportesCompartirPdf = "reportes.compartir.pdf"
    case reportesGuardarPdf = "reportes.guardar.pdf"
    case reportesCompartirCsv = "reportes.compartir.csv"
    case reportesGuardarCsv = "reportes.guardar.csv"
    case reportesVaciaTitulo = "reportes.vacia.titulo"
    case reportesTransaccionesConteo = "reportes.transacciones.conteo"
    case reportesSeleccionaMes = "reportes.selecciona_mes"
    case reportesSinDatosMes = "reportes.sin_datos_mes"
    case reportesIncluir = "reportes.incluir"
    case reportesGenerarPdf = "reportes.generar.pdf"
    case reportesGenerarCsv = "reportes.generar.csv"
    case reportesSinDatos = "reportes.sin_datos"
    case reportesErrorPdf = "reportes.error.pdf"
    case reportesErrorPdfMsg = "reportes.error.pdf.msg"
    case reportesErrorPdfSug = "reportes.error.pdf.sug"
    case reportesErrorCsv = "reportes.error.csv"
    case reportesErrorCsvMsg = "reportes.error.csv.msg"
    case reportesErrorCsvSug = "reportes.error.csv.sug"
    case reportesErrorGuardar = "reportes.error.guardar"
    case reportesErrorGuardarMsg = "reportes.error.guardar.msg"
    case reportesErrorGuardarSug = "reportes.error.guardar.sug"
    case reportesPanelPdf = "reportes.panel.pdf"
    case reportesPanelCsv = "reportes.panel.csv"
    case reportesCompartir = "reportes.compartir"

    case respaldoTitulo = "respaldo.titulo"
    case respaldoVersion = "respaldo.version"
    case respaldoCrear = "respaldo.crear"
    case respaldoImportar = "respaldo.importar"
    case respaldoImportarWindows = "respaldo.importar_windows"
    case respaldoRefrescar = "respaldo.refrescar"
    case respaldoVacioTitulo = "respaldo.vacio.titulo"
    case respaldoVacioDesc = "respaldo.vacio.desc"
    case respaldoMostrarFinder = "respaldo.mostrar_finder"
    case respaldoRestaurar = "respaldo.restaurar"
    case respaldoEliminar = "respaldo.eliminar"
    case respaldoAlertRestaurarTitulo = "respaldo.alert.restaurar.titulo"
    case respaldoAlertRestaurarMsg = "respaldo.alert.restaurar.msg"
    case respaldoAlertEliminarTitulo = "respaldo.alert.eliminar.titulo"
    case respaldoAlertEliminarMsg = "respaldo.alert.eliminar.msg"
    case respaldoDialogElegirModo = "respaldo.dialog.elegir_modo"
    case respaldoDialogMsg = "respaldo.dialog.msg"
    case respaldoOpcionCompleto = "respaldo.opcion.completo"
    case respaldoOpcionConservar = "respaldo.opcion.conservar"
    case respaldoOpcionAjustar = "respaldo.opcion.ajustar"
    case respaldoOpcionCancelar = "respaldo.opcion.cancelar"
    case respaldoAjustarSheetTitulo = "respaldo.ajustar_sheet.titulo"
    case respaldoAjustarSheetDesc = "respaldo.ajustar_sheet.desc"
    case respaldoAjustarYRestaurar = "respaldo.ajustar_y_restaurar"
    case respaldoOpcionesSaldo = "respaldo.opciones_saldo"
    case respaldoRestaurarCompleto = "respaldo.restaurar_completo"
    case respaldoEfectivo = "respaldo.efectivo"
    case respaldoTarjeta = "respaldo.tarjeta"
    case respaldoImportarPanel = "respaldo.importar_panel"
    case respaldoCreado = "respaldo.creado"
    case respaldoEliminado = "respaldo.eliminado"
    case respaldoImportado = "respaldo.importado"
    case respaldoExitoArchivo = "respaldo.exito.archivo"
    case respaldoExitoActual = "respaldo.exito.actual"
    case respaldoExitoAjustar = "respaldo.exito.ajustar"
    case respaldoErrorListar = "respaldo.error.listar"
    case respaldoErrorCrear = "respaldo.error.crear"
    case respaldoErrorEliminar = "respaldo.error.eliminar"
    case respaldoErrorImportar = "respaldo.error.importar"
    case respaldoErrorRestaurar = "respaldo.error.restaurar"
    case respaldoErrorSinBalance = "respaldo.error.sin_balance"

    case wiTitulo = "wi.titulo"
    case wiPaso1 = "wi.paso.1"
    case wiLeyendo = "wi.leyendo"
    case wiPaso2 = "wi.paso.2"
    case wiPaso3 = "wi.paso.3"
    case wiPaso4 = "wi.paso.4"
    case wiCompletado = "wi.completado"
    case wiSeleccionaTitulo = "wi.selecciona.titulo"
    case wiSeleccionaDesc = "wi.selecciona.desc"
    case wiElegirArchivo = "wi.elegir_archivo"
    case wiAnalizando = "wi.analizando"
    case wiResolverTitulo = "wi.resolver.titulo"
    case wiResolverDesc = "wi.resolver.desc"
    case wiMarcarTodasGasto = "wi.marcar_todas_gasto"
    case wiOmitirTodas = "wi.omitir_todas"
    case wiTipoOriginal = "wi.tipo_original"
    case wiMapeoGasto = "wi.mapeo.gasto"
    case wiMapeoIngreso = "wi.mapeo.ingreso"
    case wiMapeoOmitir = "wi.mapeo.omitir"
    case wiResumenArchivo = "wi.resumen.archivo"
    case wiResumenTransacciones = "wi.resumen.transacciones"
    case wiResumenIngresos = "wi.resumen.ingresos"
    case wiResumenGastos = "wi.resumen.gastos"
    case wiResumenPrestamos = "wi.resumen.prestamos"
    case wiResumenSuscripciones = "wi.resumen.suscripciones"
    case wiResumenInventario = "wi.resumen.inventario"
    case wiResumenSaldo = "wi.resumen.saldo"
    case wiSaldoTitulo = "wi.saldo.titulo"
    case wiSaldoArchivo = "wi.saldo.archivo"
    case wiSaldoActual = "wi.saldo.actual"
    case wiSaldoAjustar = "wi.saldo.ajustar"
    case wiEfectivoReal = "wi.efectivo_real"
    case wiTarjetaReal = "wi.tarjeta_real"
    case wiCalcular = "wi.calcular"
    case wiPrimerasTransacciones = "wi.primeras_transacciones"
    case wiPrestamosPrimeros = "wi.prestamos.primeros"
    case wiSinPrestamos = "wi.sin_prestamos"
    case wiSuscripcionesPrimeras = "wi.suscripciones.primeras"
    case wiSuscripcionesNoReconocidas = "wi.suscripciones.no_reconocidas"
    case wiAutoBackupTitulo = "wi.auto_backup.titulo"
    case wiAutoBackupDesc = "wi.auto_backup.desc"
    case wiImportando = "wi.importando"
    case wiImportandoDesc = "wi.importando.desc"
    case wiImportandoTitulo = "wi.importando.titulo"
    case wiImportandoSubtitulo = "wi.importando.subtitulo"
    case wiResultadoTx = "wi.resultado.tx"
    case wiResultadoPrestamos = "wi.resultado.prestamos"
    case wiResultadoSuscripciones = "wi.resultado.suscripciones"
    case wiResultadoOmitidas = "wi.resultado.omitidas"
    case wiResultadoInventario = "wi.resultado.inventario"
    case wiResultadoSaldo = "wi.resultado.saldo"
    case wiResultadoSi = "wi.resultado.si"
    case wiResultadoNo = "wi.resultado.no"
    case wiRespaldoPrevio = "wi.respaldo.previo"
    case wiRespaldoCreado = "wi.respaldo.creado"
    case wiImportar = "wi.importar"
    case wiTodasOmitidas = "wi.todas_omitidas"
    case wiSaldoExplicacionArchivo = "wi.saldo.explicacion.archivo"
    case wiSaldoExplicacionActual = "wi.saldo.explicacion.actual"
    case wiSaldoExplicacionAjustar = "wi.saldo.explicacion.ajustar"

    case ajustesTitulo = "ajustes.titulo"
    case ajustesCerrar = "ajustes.cerrar"
    case tabConfiguracion = "tab.configuracion"
    case tabRespaldos = "tab.respaldos"
    case tabLimpiar = "tab.limpiar"
    case tabDiagnostico = "tab.diagnostico"

    case diagTitulo = "diag.titulo"
    case diagDesc = "diag.desc"
    case diagBotonInfo = "diag.boton.info"
    case diagBotonWarning = "diag.boton.warning"
    case diagBotonCritical = "diag.boton.critical"
    case diagInfoTitulo = "diag.info.titulo"
    case diagInfoMsg = "diag.info.msg"
    case diagWarningTitulo = "diag.warning.titulo"
    case diagWarningMsg = "diag.warning.msg"
    case diagWarningSug = "diag.warning.sug"
    case diagCriticalTitulo = "diag.critical.titulo"
    case diagCriticalMsg = "diag.critical.msg"
    case diagCriticalSug = "diag.critical.sug"
    case diagBotonErrorSim = "diag.boton.error_sim"
    case diagBotonErrorDB = "diag.boton.error_db"
    case diagCustomTitulo = "diag.custom.titulo"
    case diagCustomDesc = "diag.custom.desc"
    case diagCustomLabelTitulo = "diag.custom.label.titulo"
    case diagCustomLabelMsg = "diag.custom.label.msg"
    case diagCustomDisparar = "diag.custom.disparar"
    case diagCustomPlaceholderTitulo = "diag.custom.placeholder.titulo"
    case diagCustomPlaceholderMsg = "diag.custom.placeholder.msg"
    case diagHistorialTitulo = "diag.historial.titulo"
    case diagHistorialDesc = "diag.historial.desc"
    case diagHistorialVacio = "diag.historial.vacio"

    case limpiarTitulo = "limpiar.titulo"
    case limpiarSubtitulo = "limpiar.subtitulo"
    case limpiarAdvertencia = "limpiar.advertencia"
    case limpiarAdvertenciaDesc = "limpiar.advertencia.desc"
    case limpiarConteoTitulo = "limpiar.conteo.titulo"
    case limpiarConteoTransacciones = "limpiar.conteo.transacciones"
    case limpiarConteoPrestamos = "limpiar.conteo.prestamos"
    case limpiarConteoSuscripciones = "limpiar.conteo.suscripciones"
    case limpiarConteoInventario = "limpiar.conteo.inventario"
    case limpiarConteoSaldo = "limpiar.conteo.saldo"
    case limpiarConteoConfigurado = "limpiar.conteo.configurado"
    case limpiarConteoNoConfigurado = "limpiar.conteo.no_configurado"
    case limpiarBorrarTodo = "limpiar.borrar_todo"
    case limpiarVacio = "limpiar.vacio"
    case limpiarTrabajando = "limpiar.trabajando"
    case limpiarAlertTitulo = "limpiar.alert.titulo"
    case limpiarAlertBorrar = "limpiar.alert.borrar"
    case limpiarErrorConteos = "limpiar.error.conteos"
    case limpiarExito = "limpiar.exito"
    case limpiarError = "limpiar.error"
    case limpiarNota = "limpiar.nota"
    case limpiarDetalleTransacciones = "limpiar.detalle.transacciones"
    case limpiarDetallePrestamos = "limpiar.detalle.prestamos"
    case limpiarDetalleSuscripciones = "limpiar.detalle.suscripciones"
    case limpiarDetalleInventario = "limpiar.detalle.inventario"
    case limpiarDetalleSaldo = "limpiar.detalle.saldo"
    case limpiarDetalleTodos = "limpiar.detalle.todos"
    case limpiarAlertDetalle = "limpiar.alert.detalle"

    case onboardingTitulo = "onboarding.titulo"
    case onboardingSubtitulo = "onboarding.subtitulo"
    case onboardingSaldos = "onboarding.saldos"
    case onboardingEfectivo = "onboarding.efectivo"
    case onboardingTarjeta = "onboarding.tarjeta"
    case onboardingInventario = "onboarding.inventario"
    case onboardingInventarioDesc = "onboarding.inventario.desc"
    case onboardingPlaceholder0 = "onboarding.placeholder.0"

    case busqPlaceholder = "busq.placeholder"
    case busqEstadoVacioTitulo = "busq.estado.vacio.titulo"
    case busqEstadoVacioDesc = "busq.estado.vacio.desc"
    case busqEstadoSinResultadosTitulo = "busq.estado.sin_resultados.titulo"
    case busqEstadoSinResultadosDesc = "busq.estado.sin_resultados.desc"
    case busqConteoResultados = "busq.conteo.resultados"
    case busqCargando = "busq.cargando"
    case busqHintNavegar = "busq.hint.navegar"
    case busqHintAbrir = "busq.hint.abrir"
    case busqHintCerrar = "busq.hint.cerrar"

    case montoPrefijo = "monto.prefijo"
    case montoPlaceholder = "monto.placeholder"

    case updatesCheck = "updates.check"
    case updatesDisponible = "updates.disponible"
    case updatesDisponibleDesc = "updates.disponible.desc"
    case updatesDescargar = "updates.descargar"
    case updatesErrorInstalar = "updates.error.instalar"
    case updatesActualizado = "updates.actualizado"
}

private let i18nBundle: Bundle = {
    let fm = FileManager.default
    let name = "TransactApp_Models.bundle"

    // 1) Production macOS .app (Contents/Resources/)
    if let rsrc = Bundle.main.resourcePath {
        let p = "\(rsrc)/\(name)"
        if fm.fileExists(atPath: p) { return Bundle(path: p)! }
    }

    // 2) SPM path 1: main bundle child
    let p1 = Bundle.main.bundleURL.appendingPathComponent(name).path
    if fm.fileExists(atPath: p1) { return Bundle(path: p1)! }

    // 3) SPM build products relative to CWD (works during `swift test`)
    for arch in ["arm64-apple-macosx", "x86_64-apple-macosx"] {
        for cfg in ["debug", "release"] {
            let p = "\(fm.currentDirectoryPath)/.build/\(arch)/\(cfg)/\(name)"
            if fm.fileExists(atPath: p) { return Bundle(path: p)! }
        }
    }

    // 4) Walk up from Bundle.main (covers some toolchain paths)
    var dir = Bundle.main.bundleURL
    for _ in 0..<15 {
        dir = dir.deletingLastPathComponent()
        let p = dir.appendingPathComponent(name)
        if fm.fileExists(atPath: p.path) { return Bundle(url: p)! }
    }

    // 5) Last resort: Bundle.module (has hardcoded absolute build path from compile time)
    // Only safe when the bundle exists at the SPM build location (dev/CI, not production)
    if fm.fileExists(atPath: p1) || fm.currentDirectoryPath.contains(".build") {
        return Bundle.module
    }

    return Bundle.main
}()

public extension LocalizableKey {
    func localized(_ args: CVarArg...) -> String {
        let format = i18nBundle.localizedString(forKey: rawValue, value: rawValue, table: nil)
        if args.isEmpty {
            return format
        }
        return withVaList(args) { ptr in
            NSString(format: format, arguments: ptr) as String
        }
    }
}

public func Localized(_ key: LocalizableKey, _ args: CVarArg...) -> String {
    let format = i18nBundle.localizedString(forKey: key.rawValue, value: key.rawValue, table: nil)
    if args.isEmpty {
        return format
    }
    return withVaList(args) { ptr in
        NSString(format: format, arguments: ptr) as String
    }
}
class _I18NBundle {}
